# JAAS 2019 - Procesamiento de Señales en Py
## Clase 1:  Librerías para manipulación de datos numéricos

![](imagenes/workshop_logo_300x200.png)

## Índice

* [Comenzando a usar Numpy](#Comenzando-a-usar-Numpy)
* [Importando la libreria y creando un array](#Importando-la-libreria-y-creando-un-array)
* [Arrays de datos](#Arrays-de-datos)
    * [Listas y arrays](#Listas-y-arrays)
    * [Longitud y dimensiones de un array](#Longitud-y-dimensiones-de-un-array)
    * [Indizado en arrays](#Indizado-en-arrays)
    * [Operaciones matematicas entre arrays](#Operaciones-matematicas-entre-arrays)
    * [Aplicando funciones matematicas](#Aplicando-funciones-matematicas)
* [Referencias](#Referencias)
* [Licencia](#Licencia)

### Comenzando a usar Numpy

Numpy es la librería dedicada a definir vectores y matrices y realizar operaciones básicas entre ellos.

El objeto principal con el que se trabaja en numpy es un **array** de una o varias dimensiones. El mismo contiene elementos, en general de formato numérico.  Se pueden definir las siguientes características para un array de numpy:

* Los elementos que lo componen son todos de un mismo tipo o formato.
* Cuenta con una longitud, igual a la cantidad de elementos que contiene por fila; y una cantidad de ejes o dimensiones, igual a la cantidad de filas que contiene.
* Cada elemento del array posee un índice que denota su ubicación dentro del mismo.

### Importando la libreria y creando un array

Para utilizar Numpy en nuestro código, primero debemos importarla utilizando el comando `import numpy`. Existen varias formas de importar librerías en  Python. La primera es ingresando `import numpy as np`, y la segunda consiste en ingresar `from numpy import * `. 
Veamos en el ejemplo, cómo ‘llamamos’ a la misma para utilizarla en nuestro código. 

Una vez importada la librería, podemos crear un array de datos. Para hacerlo, utilizamos el objeto `numpy.array` de la siguiente manera:

In [2]:
# 1° forma
import numpy

# 2° forma
from numpy import *

# 3° forma
import numpy as np

Por convención general, se suele utilizar la tercera forma para la importación de numpy. Es una forma de abreviar el nombre de la librería, y mantener la referencia de que estamos utilizando elementos de la misma. Esto nos importa para mantener cierto orden en nuestro código, por más que parezca tedioso estar anteponiendo 'np' cada vez que creamos numpy. En los ejemplos subsiguientes, vamos a considerar que se utilizó este método.

## Arrays de datos

### Listas y arrays

Nótese que al crear arrays, ésto se hace a partir de una lista, es decir que los **datos almacenados en formato de lista se convierten automáticamente en arrays**. Para ejemplificarlo mejor: 

In [9]:
# creamos el mismo array 'a' a partir de una lista

lista = [1,2,5,9]
a = np.array(lista)
type(a)
type(lista)

list

Pero, mientras en las listas se pueden incluir elementos de distinto tipo, **en el array todos deben ser un mismo tipo de datos**.

In [10]:
# otra lista con datos de distinto tipo

otra_lista = ["bla", 1, True, 3.14]

# si la intentamos convertir en array, ¿fracasamos?:

x = np.array(otra_lista)

# le pedimos a la consola que nos muestre el array
x

array(['bla', '1', 'True', '3.14'], dtype='<U4')

Vemos que el array se crea a partir de una lista con elementos de distinto tipo. Sin embargo, le asigna a todos un mismo formato, en este caso un string del tipo *Unicode* con longitud igual a 4.

## Longitud y dimensiones de un array

Los ejemplos mencionados hasta ahora han sido de arrays de una dimensión. Podemos crear **arrays de varias dimensiones** de la siguiente manera:

In [17]:
# array de dos dimensiones y longitud igual a 3
b = np.array([[1,2,3],[3,2,1]], dtype = np.uint8)

# array de tres dimensiones y longitud igual a 2
c = np.array([[1,-1],[0,1],[-5,2]])
b.shape

(2, 3)

La **longitud** representa la cantidad de elementos que posee el array en sus filas. Su valor, y el de las dimensiones de un array, se pueden obtener de la siguiente manera: 

In [19]:
# devuelve la forma de un array, de la siguiente forma (n° de filas, n° de columnas)
(dimensiones, longitud) = b.shape
longitud

3

## Indizado en arrays

Los **índices** se utilizan para indicar la posición de cada elemento de un array. De esta manera, podemos acceder al valor de una posición específica o extraer el valor de un grupo de elementos. Cada elemento posee una posición *[i,j]*, donde 'i' representa el número de fila y 'j' representa el número  de columna en que se ubica.

In [25]:
# devuelve el elemento de la posición [1,2] del array 'a', igual a 2.
#print(b[1,0])

# devuelve el elemento de la posición [2,0] del array 'b', igual a -5.
print(c[2,1])


2


In [28]:
fibo = np.array([0,1,1,2,3,5,8,13,21,34], dtype = np.uint8)
print (fibo[1:8:2])

[ 1  2  5 13]


Es importante tener en cuenta que los índices que se asignan se inician desde 0, por lo que si tengo 4 elementos, sus índices irán del rango de 0 a 3.
Podemos **desplazarnos** dentro de una array, y **seleccionar** un rango de elementos utilizando la notación *[i: j: k]*, donde 'i' representa el índice a partir del cual nos desplazamos, 'j' es el índice en el cual nos detenemos y 'k' es el paso con el cual nos desplazamos a los elementos subsiguientes. 

In [33]:
fibo = np.array([0,1,1,2,3,5,8,13,21,34], dtype = np.uint8)



# desplazamiento desde la posición 3 hasta el final del array
print (fibo[1:12])


[ 1  1  2  3  5  8 13 21 34]


## Operaciones matematicas entre arrays

Las operaciones matemáticas entre arrays se realizan **elemento a elemento**. Esto quiere decir que si sumamos dos arrays 'a' y 'b', el elemento *a[i,j]* se suma con el elemento *b[i,j]*. Por lo tanto, debemos operar entre arrays de iguales tamaños (aunque existen excepciones, las cuales veremos en el apartado ['broadcasting'](#Broadcasting)).

In [34]:
import numpy as np

a = np.array([1,2,3,1], dtype = np.uint8)
b = np.array([2,4,2,1], dtype = np.uint8)

In [35]:
# producto por escalar
5 * a

array([ 5, 10, 15,  5], dtype=uint8)

In [36]:
# suma de arrays (la resta es igual)
a + b

array([3, 6, 5, 2], dtype=uint8)

In [37]:
# producto de arrays (elemento a elemento)
a * b

array([2, 8, 6, 1], dtype=uint8)

In [38]:
# producto matricial entre arrays
a.dot(b)

17

In [39]:
# cociente de arrays
a / b

array([0.5, 0.5, 1.5, 1. ])

In [40]:
# potencia de arrays (?)
a**b

array([ 1, 16,  9,  1], dtype=uint8)

In [41]:
# operación módulo
a % b

array([1, 2, 1, 0], dtype=uint8)

In [42]:
# ahora intento de nuevo convirtiendo el formato de 'a' a un float
a = np.array([1,2,3,1], dtype = np.float16)

# y entonces...
a**b

array([ 1., 16.,  9.,  1.], dtype=float16)

## Aplicando funciones matematicas

Numpy dispone de varias funciones matemáticas para aplicar sobre un simple escalar o sobre un array. En esta sección nos enfocaremos en la creación de funciones trigonométricas y logarítmicas específicamente. La lista completa de funciones matemáticas que provee Numpy puede verse haciendo [clic acá](https://docs.scipy.org/doc/numpy/reference/routines.math.html#trigonometric-functions).

Veamos algunos ejemplos:

In [61]:
# multiplico una array por el escalar pi.
x = np.array([0, .55, 1, 1.5])*np.pi
x

array([0.        , 1.72787596, 3.14159265, 4.71238898])

In [62]:
f_seno = np.sin(x).round(2)

print(f_seno)

[ 0.    0.99  0.   -1.  ]


In [64]:
f_coseno = np.cos(x).round()

print(f_coseno)

[ 1. -0. -1. -0.]


Entonces, podemos crear arrays para representar funciones matemáticas conocidas. Primero creamos un array para definir una serie de puntos en el dominio de la función y luego aplicamos la función sobre estos puntos.

En los últimos ejemplos, podemos notar que los valores de las funciones seno y coseno se aproximaron a cero pero no fueron exactamente iguales a ese número. Esto se debe a la precisión de los formatos *float*, podemos hacer la prueba de definir *x* con floats de 32 y 64 bits y veremos que los valores se aproximan más al número deseado.

Entonces, ¿cómo podemos crear un array que represente a una función senoidal en el dominio del tiempo? Anteriormente vimos cómo crear secuencias numéricas, y una de las funciones que utilizamos fue *linspace*. Ahora vamos a aprovecharla para crear una representación de una función.

In [71]:
x = np.linspace(0, 5*np.pi, 21, dtype=np.float32)
x

array([ 0.       ,  0.7853982,  1.5707964,  2.3561945,  3.1415927,
        3.9269907,  4.712389 ,  5.497787 ,  6.2831855,  7.0685835,
        7.8539815,  8.6393795,  9.424778 , 10.210176 , 10.995574 ,
       11.7809725, 12.566371 , 13.3517685, 14.137167 , 14.922565 ,
       15.707963 ], dtype=float32)

Con *x* tenemos representados los puntos en el dominio del tiempo, ahora tenemos que generar la función trigonométrica para estos valores.

In [73]:
f_trig_1 = np.cos(x).round()

print (f_trig_1)

[ 1.  1. -0. -1. -1. -1.  0.  1.  1.  1.  0. -1. -1. -1. -0.  1.  1.  1.
 -0. -1. -1.]


Por último, un ejemplo de logaritmos. Nos sirve también para ver cómo utilizar `numpy.power` para aplicar potencias

In [80]:
import numpy as np

p_ref = 2*np.power(10.,-5)
p = np.linspace(p_ref, 1, 100) # la base en número float! -> 10.

p_log = 10*np.log10(p/p_ref)
p_log

array([ 0.        , 27.04185194, 30.04785867, 31.80733924, 33.05601042,
       34.02468078, 34.81620671, 35.48546992, 36.06523587, 36.57664169,
       37.03412107, 37.44796976, 37.82579024, 38.17335619, 38.49515578,
       38.79474707, 39.07499848, 39.33825626, 39.586464  , 39.82124981,
       40.04399113, 40.25586365, 40.4578789 , 40.65091346, 40.83573194,
       41.01300528, 41.18332544, 41.34721736, 41.50514865, 41.65753773,
       41.80476042, 41.94715556, 42.08502974, 42.21866121, 42.34830332,
       42.47418737, 42.59652511, 42.71551088, 42.83132349, 42.94412779,
       43.05407613, 43.16130954, 43.26595888, 43.36814577, 43.46798343,
       43.56557746, 43.66102649, 43.75442277, 43.84585276, 43.93539753,
       44.02313326, 44.10913161, 44.19346004, 44.27618218, 44.35735808,
       44.43704448, 44.51529506, 44.59216065, 44.66768943, 44.7419271 ,
       44.81491706, 44.88670056, 44.95731683, 45.02680323, 45.09519534,
       45.1625271 , 45.22883088, 45.29413761, 45.35847682, 45.42

In [84]:
p_log[-2]

46.94560974062482

## Referencias

 * *Numpy User Guide*, https://www.numpy.org/

 * Scott Shell, *An introduction to Numpy and Scipy*, 2014. 

## Licencia

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />Este documento se destribuye con una <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">licencia Atribución CompartirIgual 4.0 Internacional de Creative Commons</a>.

© 2019. Infiniem Lab DSP. **infiniemlab.dsp@gmail.com**. ICurso de Procesamiento de Señales en Python (CC BY-SA 4.0)